application: stunning-net-216
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /test.*
   script: gaeunit.application
 - url: /.*
   script: main.application

libraries:
 - name: webapp2
   version: latest
 - name: jinja2
   version: latest
 - name: django
   version: latest

